mongodb/docs-atlas-architecture

snooty.toml, source/changelog.txt, source/index.txt
Adds a changelog to the Architecture Center
[DOCSP](https://jira.mongodb.org/browse/DOCSP-44579)
[STAGING](https://deploy-preview-17--docs-atlas-architecture.netlify.app/changelog/)
=> Adds a changelog

snooty.toml, source/automation.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-43339)
- [Stage](https://deploy-preview-14--docs-atlas-architecture.netlify.app/automation/)
=> DOCSP-43339 doc for Automation

source/getting-started.txt, source/hierarchy.txt
Waiting on diagrams from design, but otherwise ready for review. I'll merge it for the first draft and add the diagrams when they're ready.
[DOCSP](https://jira.mongodb.org/browse/DOCSP-43341)
[STAGING](https://deploy-preview-13--docs-atlas-architecture.netlify.app/hierarchy/)
The org create command was tested successfully, see screenshots below:
=> (DOCSP-43341) Adds reframed hierarchy page

source/includes/cloud-docs/shared-migration-cutover-description.rst, source/includes/cloud-docs/shared-migration-monitoring-description.rst, source/includes/cloud-docs/shared-migration-tools-table.rst, source/migration.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-43338)
[STAGING](https://deploy-preview-19--docs-atlas-architecture.netlify.app/migration/#std-label-arch-center-migration)
=> Adds first draft of Migrations doc.

source/backups.txt, source/includes/examples/cli-example-backup-compliance-policy-enable.rst, source/includes/examples/cli-example-backup-compliance-policy-schedule.rst, source/includes/examples/cli-example-backup-take-snapshot.rst, source/includes/examples/tf-example-backup-snapshot-pit-restore.rst, source/includes/examples/tf-example-backup-snapshot-schedule.rst, source/includes/examples/tf-example-backup-variables.rst
- [JIRA](https://jira.mongodb.org/browse/DOCSP-43349)
- [Stage](https://deploy-preview-25--docs-atlas-architecture.netlify.app/backups/)
=> DOCSP-43349 Backups doc

source/auditing-logging.txt, source/includes/cloud-docs/logs.rst, source/includes/examples/tf-example-auditing-filter.rst, source/landing-zone.txt, source/monitoring-alerts.txt
[DOCSP-43346](https://jira.mongodb.org/browse/DOCSP-43346)
@lantoli , @fmenezes , I reused the example from this [auditing.md file](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/c34e0a96f52df398dbddfcb29c84f264e311f222/docs/resources/auditing.md) from the Terraform repo.
Staging link:
[Auditing and Logging](https://deploy-preview-33--docs-atlas-architecture.netlify.app/auditing-logging/)
=> (DOCSP-43346) Auditing and Logging

source/includes/examples/cli-json-example-create-clusters-with-autoscaling.rst, source/includes/examples/tf-example-autoscaling-main-stagingprod.rst, source/includes/examples/tf-example-autoscaling-variables.rst, source/includes/examples/tf-example-tfvars-autoscaling-stagingprod.rst, source/includes/shared-settings-clusters-stagingprod.rst, source/scalability.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-43350)
[STAGING](https://deploy-preview-35--docs-atlas-architecture.netlify.app/scalability/#scalability)
[BUILD](https://app.netlify.com/sites/docs-atlas-architecture/deploys/67362680eca5370008b80f48)
=> (DOCSP-43350) scalability architecture center first draft

source/resiliency.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45856)
[Staging](https://deploy-preview-50--docs-atlas-architecture.netlify.app/resiliency/#std-label-resiliency-read-write-concerns)
=> (DOCSP-45856) Revises per explicit edits from v1 review.

source/backups.txt, source/includes/examples/cli-example-backup-compliance-policy-enable.rst
[Jira](https://jira.mongodb.org/browse/DOCSP-45891)
[Staging](https://deploy-preview-51--docs-atlas-architecture.netlify.app/backups/)
=> (DOCSP-45891) Revises per explicit edits from v1 review.

source/network-security.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45897)
[Staging](https://deploy-preview-52--docs-atlas-architecture.netlify.app/network-security/)
=> (DOCSP-45897) Revises per explicit edits from v1 review.

source/auth.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45900)
[Staging](https://deploy-preview-53--docs-atlas-architecture.netlify.app/auth/)
=> (DOCSP-45900) Revises per explicit edits from v1 review.

source/scalability.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45948)
[Staging](https://deploy-preview-57--docs-atlas-architecture.netlify.app/scalability/)
=> (DOCSP-45948) Revises per explicit edits from v1 review.

source/auditing-logging.txt, source/includes/cloud-docs/logs.rst
[Jira](https://jira.mongodb.org/browse/DOCSP-45941)
[Staging](https://deploy-preview-56--docs-atlas-architecture.netlify.app/auditing-logging/)
=> (DOCSP-45941) Revises per explicit edits from v1 review.

source/data-encryption.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45910)
[Staging](https://deploy-preview-54--docs-atlas-architecture.netlify.app/data-encryption/)
=> (DOCSP-45910) Revises per explicit edits from v1 review.

source/compliance.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45917)
[Staging](https://deploy-preview-55--docs-atlas-architecture.netlify.app/compliance/)
=> (DOCSP-45917) Revises per explicit edits from v1 review.

source/backups.txt, source/compliance.txt
https://deploy-preview-60--docs-atlas-architecture.netlify.app/compliance/
=> Updates to compliance page

snooty.toml, source/cost-optimization.txt, source/cost-saving-config.txt, source/data-encryption.txt, source/high-availability.txt, source/operational-efficiency.txt, source/performance.txt, source/reliability.txt, source/resiliency.txt, source/security.txt
https://jira.mongodb.org/browse/DOCSP-45646
@sarahsimpers I added content for five pillar pages.
This second draft has no URL paths and no images, but other items are included. 
Staging links:
1. [Operational Efficiency](https://deploy-preview-47--docs-atlas-architecture.netlify.app/operational-efficiency/)
2. [Security](https://deploy-preview-47--docs-atlas-architecture.netlify.app/security/)
3. [Reliability](https://deploy-preview-47--docs-atlas-architecture.netlify.app/reliability/)
4. [Performance](https://deploy-preview-47--docs-atlas-architecture.netlify.app/performance/)
5. [Cost Optimization](https://deploy-preview-47--docs-atlas-architecture.netlify.app/cost-optimization/)
=> (DOCSP-45646) Pillar content

source/backups.txt, source/includes/examples/cli-example-backup-compliance-policy-schedule.rst
- [JIRA](https://jira.mongodb.org/browse/DOCSP-46048)
- [Stage](https://deploy-preview-66--docs-atlas-architecture.netlify.app/backups/)
=> DOCSP-46048 First-Round Edits: Backups Page

source/auth.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-46049)
- [Stage](https://deploy-preview-64--docs-atlas-architecture.netlify.app/auth/)
=> DOCSP-46049 First-Round Edits: Auth Page

source/disaster-recovery.txt, source/monitoring-alerts.txt
Addresses Ian's comments in this document: https://docs.google.com/document/d/1yqHYGYzvs6NccQfnLA4qVe1PplV2dWEBq9kKyidfnWk/edit?tab=t.0#heading=h.7pibw5vqg0j
Staging: https://deploy-preview-46--docs-atlas-architecture.netlify.app/monitoring-alerts/
=> Makes Ian's updates to the monitoring page

source/high-availability.txt, source/scalability.txt
[STAGING](https://deploy-preview-70--docs-atlas-architecture.netlify.app/scalability/)
=> (DOCSP-46050) addressing Ian's feedback

source/network-security.txt
Staging: https://deploy-preview-77--docs-atlas-architecture.netlify.app/network-security/#vpc-vnet-peering
=> Fixes typo- space missing

source/data-encryption.txt, source/hierarchy.txt, source/includes/byok-encryption-recommendations-short.rst, source/includes/byok-encryption-recommendations.rst, source/includes/examples/tf-example-byok-aws.rst, source/includes/examples/tf-example-byok-azure.rst, source/includes/examples/tf-example-byok-gcp.rst, source/includes/shared-settings-clusters-stagingprod.rst
[DOCSP-46242](https://jira.mongodb.org/browse/DOCSP-46242)
Staging:
- https://deploy-preview-76--docs-atlas-architecture.netlify.app/hierarchy/
- https://deploy-preview-76--docs-atlas-architecture.netlify.app/data-encryption/
=> (DOCSP-46242): Add BYOK Encryption examples

source/includes/billing-optimizations.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-44841)
[Staging](https://deploy-preview-83--docs-atlas-architecture.netlify.app/cost-saving-config/)
=> DOCSP-44841 round 2 edits cost saving config page

source/index.txt, source/landing-zone.txt
Staging: https://deploy-preview-86--docs-atlas-architecture.netlify.app/
=> (DOCSP-44660) Second draft edits to index, landing zones pages

source/billing-data.txt
Staging: https://deploy-preview-87--docs-atlas-architecture.netlify.app/billing-data/
=> (DOCSP-44840) Second draft edits to the Billing Data page

source/auditing-logging.txt
Staging: https://deploy-preview-89--docs-atlas-architecture.netlify.app/auditing-logging/
=> (DOCSP-44994) Second draft edits to the Auditing and Logging page

source/backups.txt, source/includes/examples/tf-example-backup-snapshot-schedule-tier1.rst, source/includes/examples/tf-example-backup-snapshot-schedule-tier2.rst, source/includes/examples/tf-example-backup-snapshot-schedule-tier3.rst, source/includes/examples/tf-example-backup-variables.rst
- [JIRA](https://jira.mongodb.org/browse/DOCSP-44993)
- [Stage](https://deploy-preview-94--docs-atlas-architecture.netlify.app/backups/)
=> DOCSP-44993 Updates for Second Draft: Backups Page

source/resiliency.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-44991)
[STAGING]()
=> DOCSP-44991 -- Resiliency 2nd Draft

source/getting-started.txt, source/index.txt
Staging: https://deploy-preview-81--docs-atlas-architecture.netlify.app/
=> Adds cards for pillars to landing page

source/high-availability.txt
- [DOCSP-44990](https://jira.mongodb.org/browse/DOCSP-44990)
- [STAGING](https://deploy-preview-95--docs-atlas-architecture.netlify.app/high-availability/)
- [LATEST BUILD LOG](https://app.netlify.com/sites/docs-atlas-architecture/deploys/679a6ef2145c970008b25a0e)
=> (DOCSP-44990) Updating High Availability Page

source/includes/cloud-docs/shared-metric-description-cpu.rst, source/includes/cloud-docs/shared-metric-description-iops.rst, source/includes/cloud-docs/shared-metric-description-latency.rst, source/includes/cloud-docs/shared-metric-description-memory.rst, source/includes/cloud-docs/shared-metric-description-oplog-window.rst, source/includes/cloud-docs/shared-metric-description-page-faults.rst, source/includes/cloud-docs/shared-metric-description-replication-lag.rst, source/monitoring-alerts.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-44989)
[Staging](https://deploy-preview-91--docs-atlas-architecture.netlify.app/monitoring-alerts/#recommended-atlas-alert-configurations)
=> (DOCSP-44989) Revises per second-draft edits.

source/monitoring-alerts.txt
Staging: https://deploy-preview-98--docs-atlas-architecture.netlify.app/monitoring-alerts/
=> Makes second draft edits to the Monitoring page

source/auth.txt, source/includes/examples/cli-example-auth-oid-devtest.rst, source/includes/examples/tf-example-auth-oidc-devtest.rst, source/includes/examples/tf-example-auth-tfazure.rst, source/includes/examples/tf-example-auth-tfoutputs-devtest.rst, source/includes/examples/tf-example-auth-tfvars-devtest.rst, source/includes/examples/tf-example-auth-variables-devtest.rst, source/includes/examples/tf-example-main-stagingprod.rst, source/includes/examples/tf-example-tfvars-stagingprod.rst, source/includes/examples/tf-example-variables.rst
- [JIRA](https://jira.mongodb.org/browse/DOCSP-46239)
- Stage:
- https://deploy-preview-75--docs-atlas-architecture.netlify.app/auth/#examples
- https://deploy-preview-75--docs-atlas-architecture.netlify.app/hierarchy/#create-one-cluster-per-project
=> DOCSP-46239 Update examples on Authorization and Authentication page

source/auth.txt, source/hierarchy.txt
Staging: https://deploy-preview-100--docs-atlas-architecture.netlify.app/auth/
=> (DOCSP-44997) Remaining Auth page second-draft edits after Elyse PR

source/scalability.txt
[BUILD](https://app.netlify.com/sites/docs-atlas-architecture/deploys/679a9de98dca110008c9743c)
[STAGING](https://deploy-preview-99--docs-atlas-architecture.netlify.app/scalability/)
=> (DOCSP-44842) copy fix from stakeholders

source/network-security.txt
[BUILD](https://app.netlify.com/sites/docs-atlas-architecture/deploys/679bf27d265aca0008f67abe)
[STAGING](https://deploy-preview-102--docs-atlas-architecture.netlify.app/network-security/#network-security)
=> (DOCSP-44659) addressing feedback from stakeholders

source/hierarchy.txt
=> (DOCSP-44489) stakeholder feedback

source/disaster-recovery.txt
https://jira.mongodb.org/browse/DOCSP-46410
Ready for review.
=> (DOCSP-46410) Address tech review comments for Disaster Recovery docs

source/disaster-recovery.txt
This is a follow up PR to this PR and it includes copy edits from #104.
=> Edits for disaster recovery, from the previous PR #104

source/security.txt
Staging: https://deploy-preview-121--docs-atlas-architecture.netlify.app/security/
Confirmed the cards now point to the right place
=> (DOCSP-47913) Fixes card bugs on Security page

source/hierarchy.txt
Make the following edits from the Final Review doc:
- [Developing with MongoDB at your org/Atlas CLI section or edits](https://docs.google.com/document/d/1tl0rixvJvU0Tg1jigVh38c0F0KFpsYtg6tVX8MKNOZ4/edit?disco=AAABcN0gpUY)
- [Adjust cluster hierarchy section](https://docs.google.com/document/d/1tl0rixvJvU0Tg1jigVh38c0F0KFpsYtg6tVX8MKNOZ4/edit?disco=AAABcM38eWk)
- [Real-world examples (provided by Ian in doc)](https://docs.google.com/document/d/1tl0rixvJvU0Tg1jigVh38c0F0KFpsYtg6tVX8MKNOZ4/edit?disco=AAABcM38eWM)
- [DOCSP-47820](https://jira.mongodb.org/browse/DOCSP-47820)
- [STAGING](https://deploy-preview-129--docs-atlas-architecture.netlify.app/hierarchy/)
=> (DOCSP-47820) [Atlas Architecture] Make follow-up edits from the Orgs, Projects, and Clusters page

source/release-notes.txt
[DOCSP ticket](https://jira.mongodb.org/browse/DOCSP-48480)
[Staging](https://deploy-preview-135--docs-atlas-architecture.netlify.app/release-notes/)
=> (DOCSP-48480) Adds release notes for March 17 2025 release

source/multi-cloud.txt
[DOCSP](https://jira.mongodb.org/browse/DOCSP-48778)
[Staging](https://deploy-preview-145--docs-atlas-architecture.netlify.app/multi-cloud/#recommendations-for-multi-cloud-deployments)
=> (DOCSP-48778) Updates language in callout on multi-cloud page

source/hybrid.txt
https://jira.mongodb.org/browse/DOCSP-49211
https://deploy-preview-168--docs-atlas-architecture.netlify.app/hybrid/
=> Revamp hybrid page to match others and reduce redundancy

source/includes/images/industry-solutions/Wind-Turbine-Diagnosis-Demo.svg, source/industry-solutions/audio-based-AI-diagnostics.txt
Fixes build error:
WARNING(industry-solutions/audio-based-AI-diagnostics.txt:201ish): Explicit markup ends without a blank line; unexpected unindent.
https://deploy-preview-175--docs-atlas-architecture.netlify.app/industry-solutions/audio-based-AI-diagnostics/
https://jira.mongodb.org/browse/DOCSP-49157
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)
=> DOCSP-49157-2 fixing build

source/release-notes.txt
Add a release note entry for the multi-region release with a tentative release date of July 11, 2025 (to be updated with actual date at release time).
You can find all the content we're adding in this release in the "Content Scope" column in this doc: https://docs.google.com/document/d/1l2xkaAfsshKrkaZYJAqTClha-4jT_zhtAYYRu4nSP1k/edit?tab=t.0
[DOCSP-48697](https://jira.mongodb.org/browse/DOCSP-48697)
https://deploy-preview-161--docs-atlas-architecture.netlify.app/release-notes/
=> (DOCSP-48697) [Atlas Architecture] Add release note changes for multi-region release

source/monitoring-alerts.txt, source/network-security.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-48626)
STAGING:
- [Monitoring and Alerts](https://deploy-preview-154--docs-atlas-architecture.netlify.app/monitoring-alerts/)
- [Network Security](https://deploy-preview-154--docs-atlas-architecture.netlify.app/monitoring-alerts/)
=> (DOCSP-48626) four small final review changes.

source/deployment-paradigms.txt, source/multi-region.txt
Feedback from AndrewD, pulled from "bulk" ticket 48508:
[Put use cases in other spots where they make sense](https://docs.google.com/document/d/1mVDpIhMpvLFlcUIVU1IEfIY3kegbdSzwzm4NsgtXyrs/edit?disco=AAABe_jE3L4) with links back to the paradigm pages
[DOCSP-49244](https://jira.mongodb.org/browse/DOCSP-49244)
https://deploy-preview-183--docs-atlas-architecture.netlify.app/deployment-paradigms/
=> (DOCSP-49244) Add Use Cases to Deployment Paradigms

source/includes/complete-examples.rst, source/includes/examples/tf-dev-test-complete/aws-roles.tf, source/includes/examples/tf-dev-test-complete/azure.tf, source/includes/examples/tf-dev-test-complete/encryption.tf, source/includes/examples/tf-dev-test-complete/main.tf, source/includes/examples/tf-dev-test-complete/private_link.tf, source/includes/examples/tf-dev-test-complete/provider.tf, source/includes/examples/tf-dev-test-complete/terraform.tfvars, source/includes/examples/tf-dev-test-complete/variables.tf
Creating a unified Terraform example for Dev/Test - this PR takes the dev/test code examples from all pages and combines it into a single directory. The code added in this PR mirrors existing code with some minor updates to allow the different code examples to work together in a single TF instance.
=> Create unified TF example for dev & test

source/backups.txt, source/index.txt, source/landing-zone.txt, source/network-security.txt, source/operational-readiness-checklist.txt, source/performance.txt
This PR adds an operational readiness checklist, as requested in the [DOCSP-42567](https://jira.mongodb.org/browse/DOCSP-42567).
Staging: [Operational Readiness Checklist](https://deploy-preview-177--docs-atlas-architecture.netlify.app/operational-readiness-checklist/)
Context: the content is based on the following sources:
- [Hard-coded certs section](https://www.mongodb.com/docs/atlas/reference/faq/security/#hard-coded-certificate-authority) in the Atlas docs
- [Landing zone considerations](https://www.mongodb.com/docs/atlas/architecture/current/landing-zone/#what-are-some-important-landing-zone-considerations-) from this same guide
- [MongoDB Launch Success List](https://www.mongodb.com/services/customer-success-program/launch-readiness-checklist) from the MongoDB corporate website
- …
=> (DOCSP-42567) Operational readiness checklist

snooty.toml, source/landing-zone.txt, source/monitoring-alerts.txt, source/network-security.txt
Make the following edits to the Architecture Center from the Final Review doc:
- Added default settings to the Security box in the [Considerations Table](https://deploy-preview-186--docs-atlas-architecture.netlify.app/landing-zone/#critical-considerations)
Please merge these changes to the release branch. Do not backport or publish.
[DOCSP-47815](https://jira.mongodb.org/browse/DOCSP-47815)
https://deploy-preview-186--docs-atlas-architecture.netlify.app/landing-zone/
=> (DOCSP-47815) [Atlas Architecture] Make follow-up edits from the Landing Zones page

source/getting-started.txt, source/index.txt, source/landing-zone.txt, source/migration.txt
[STAGING](https://deploy-preview-192--docs-atlas-architecture.netlify.app/migration/)
=> (DOCSP-44848) Migration page round two

source/auth/authentication.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-50189)
[STAGING](https://deploy-preview-231--docs-atlas-architecture.netlify.app/auth/authentication/#service-accounts)
=> (DOCSP-50189) Re-adds recs for service accounts + API keys.

source/auditing-logging.txt, source/auth/authentication.txt, source/auth/authorization.txt, source/automation.txt, source/backups.txt, source/data-encryption.txt, source/hierarchy.txt, source/monitoring-alerts.txt, source/network-security.txt, source/scalability.txt
Update `/includes/complete-examples.rst` includes to point to renamed `/includes/complete-examples-terraform.rst` file
=> Populate file rename to resolve build errors

source/solutions-library/credit-card-application-with-generative-ai.txt, source/solutions-library/hasura-fintech-services.txt
Implement edits to the [Credit Card Application](https://www.mongodb.com/docs/atlas/architecture/current/solutions-library/credit-card-application-with-generative-ai/) solution to make the tone / style a bit more in line with docs.
This PR was reviewed in #255, but that PR was pointing to the wrong branch (`release`), so I'm opening this PR with the same changes but pointing to `main`.
https://deploy-preview-263--docs-atlas-architecture.netlify.app/solutions-library/credit-card-application-with-generative-ai/
https://jira.mongodb.org/browse/DOCSP-49726
=> DOCSP-49726-credit-card-app-poc-edits

source/solutions-library.txt
Description
-----------
Update industry names to shorten index names and cards tabs. All industry visible on landing page.
- Manufacturing and Motion to Manufacturing
- Telecommunications to Telco
Staging
--------
[Industry Solutions](https://deploy-preview-276--docs-atlas-architecture.netlify.app/solutions-library/)
=> Update Industry names - Manufacturing and Telco

source/solutions-library/media-personalization.txt, source/solutions-library/pdf-search.txt
https://jira.mongodb.org/browse/DOCSP-51695 and https://jira.mongodb.org/browse/DOCSP-51696 on accident
Copy edit PDF search page and AI-driven media personalization page.
https://deploy-preview-277--docs-atlas-architecture.netlify.app/solutions-library/pdf-search/
https://deploy-preview-277--docs-atlas-architecture.netlify.app/solutions-library/media-personalization
=> DOCSP-51695: [IS Edits] Build a PDF Search Application with Vector Search and LLMs

source/solutions-library/claim-management.txt, source/solutions-library/insurance-gen-ai.txt
Rewording https://www.mongodb.com/docs/atlas/architecture/current/solutions-library/claim-management/ so it fits with our docs writing style.
https://jira.mongodb.org/browse/DOCSP-51698
https://deploy-preview-282--docs-atlas-architecture.netlify.app/solutions-library/claim-management/
=> DOCSP-51698-llm-rag-claim-management
